#!/bin/sh

read -p "Would you like to create a new home directory tree? [y/n]  " user_choice
if [ "$user_choice" = "y" ]; then
	echo "Creating new directory structure"
	dirs=$(cat "dirs")
	for x in $dirs; do
		#echo "$HOME/$x"
		mkdir -pv "$HOME/$x"
	done
fi

read -p "Would you like to move the repo before linking? [y/n]  " user_choice
if [ "$user_choice" = "y" ]; then
	repo_destination="$HOME/repos/void-dots"
	read -p "Where would you like to move it to? Default '$repo_destination'  " user_choice
	[ -z "$user_choice" ] || repo_destination="$user_choice"
	[ -d "$(dirname $repo_destination)" ] || mkdir -pv "$(dirname $repo_destination)"
	mv "$(pwd)" "$repo_destination"
	cd "$repo_destination"
fi

source .profile
./linkfiles
