#!/bin/sh

target_names=$(cat targets)

target_base="$(pwd)"
destination_base="$HOME"
storage_base="$HOME/.old_dots/$(date +'%y%m%d-%H%M%S')"

[ -z "$1" ] || target_base="$1"
[ -z "$2" ] || destination_base="$2"
[ -z "$3" ] || storage_base="$3"

#echo "Target $target_base"
#echo "Destination $destination_base"
#echo "Dotfile Storage $storage_base"

read -p "Confirm linking from '$target_base' to '$destination_base'? [y/n]  " user_choice
if [ "$user_choice" != "y" ]; then
	echo "Aborting..."
	exit
fi

read -p "Would you like to (m)ove old files to '$storage_base', (d)elete them or (u)pdate the symlinks (will create new links if they don't exist)?  " user_choice
case $user_choice in
	"m"|"M")
		echo "Moving files"
		for f in $target_names; do
			[ -d $(dirname "$storage_base/$f") ] || mkdir -pv $(dirname "$storage_base/$f")
			mv -v "$destination_base/$f" "$storage_base/$f"
		done
		;;
	"d"|"D")
		echo "Deleting files"
		for f in $target_names; do
			rm -vr "$destination_base/$f"
		done
		;;
	"u"|"U")
		;;
	*)
		;;
esac

echo "Creating directories for programs"
mkdir -pv "$HOME/.local/share/vim/backup"
mkdir -pv "$HOME/.local/share/vim/swap"
mkdir -pv "$HOME/.local/share/vim/undo"
mkdir -pv "$HOME/.local/share/vim/plugged"
mkdir -pv "$HOME/.local/share/bash"


echo "Linking files to destination '$destination_base'"

for f in $target_names; do
	[ -d $(dirname "$destination_base/$f") ] || mkdir -pv $(dirname "$destination_base/$f")
	ln -sfv "$target_base/$f" "$(dirname $destination_base/$f)"
done


