#!/bin/bash

old_location="$HOME/.old_dots"
location=$(pwd)

mv_old(){
	mv -v "$HOME/$1" "$old_location/$1"	
}

ln_new_file(){
	ln -sv "$location/$1" "$HOME/$1"
}

declare -a link_files=(".Xresources" ".bash_aliases" ".bash_profile" ".bashrc" ".profile" ".xinitrc" ".vimrc" ".vim" ".Xscripts" ".wallpaper")
declare -a link_conf_files=("nvim" "rofi" "i3" "dunst" "compton.conf" "polybar")


echo "Moving existing files in ~/ to ~/.old_dots"

[[ ! -d "$old_location" ]] && mkdir "$old_location" "$old_location/.config"

for f in "${link_files[@]}"; do
	mv_old "$f"
done

[[ ! -d "$HOME/.config" ]] && mkdir "$HOME/.config"
for f in "${link_conf_files[@]}"; do
	mv_old ".config/$f"
done


echo "Creating symlinks"

for f in "${link_files[@]}"; do
	ln_new_file "$f"
done
for f in "${link_conf_files[@]}"; do
	ln_new_file ".config/$f"
done
