#!/bin/bash

echo "Creating new directory structure"
mkdir -pv  ~/user/{Downloads,Libraries}  ~/user/Libraries/{Documents,Pictures,Programming} ~/user/Programming/{C,Cpp} ~/user/Mounts/{NAS,Memstick,Data,General1,General2,General3}
mkdir -pv ~/{.fonts,.scripts,programs,extracts}
