" .vimrc

" Get the defaults that most users want.
"source $VIMRUNTIME/defaults.vim

" Set directories for vim
set nocompatible
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viminfo=%,<800,'10,/50,:100,h,f0,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

" Misc settings
filetype plugin on
set encoding=utf-8
set number relativenumber
set tabstop=4
set shiftwidth=4

" Syntax highlighting
syntax on
set t_Co=256
colorscheme custom
autocmd BufEnter * :syntax sync fromstart

" Set the status line
set statusline=
set statusline+=\ %r
set statusline+=\ %m
set statusline+=\ %y
set statusline+=\ %F
set statusline+=%=
set statusline+=\ %c:%l/%L
set statusline+=\ [%p%%]


" netrw things
let g:netrw_banner=0
let g:netrw_altv=1
let g:netrw_liststyle=3


" vim-plug
call plug#begin('$XDG_DATA_HOME/vim/plugged')
"Plug 'abudden/taghighlight-automirror'
call plug#end()


" Copy selected text to system clipboard (requires gvim/nvim/vim-x11 installed):
vnoremap <C-c> "+y
map <C-p> "+P

" Set a bunch of leader things
" Default leader is backslash (\)
let mapleader = " "
" map <leader>h <esc>:noh<CR>


" Normal mode remaps
nnoremap <esc> :noh<CR><esc>
nnoremap <leader><left>		gT
nnoremap <leader>h			gT	
nnoremap <leader><right>	gt
nnoremap <leader>l			gt

" Navigating with guides (from LukeSmithxyz)
"inoremap <Space><Space> <Esc>/<++><Enter>"_c4l
"vnoremap <Space><Space> <Esc>/<++><Enter>"_c4l
nnoremap <Space><Space> <Esc>/<++><CR>"_c4l


" Auto run commands when things change
autocmd BufWritePre * $s/\s\+$//e			" Remove whitespace at end of lines on write
autocmd BufWritePost ~/.Xresources !xrdb %

" Setting file types that vim doesn't recognise
autocmd BufNewFile,BufReadPost *.tex set filetype=tex

" Separate file for macros
source $XDG_CONFIG_HOME/vim/file_macros.vim

