#!/bin/bash

# Persistent command flags
alias python='python3'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias la='ls -Agoh --time-style=+%y-%m-%d'
alias ll='ls -Alh --time-style=long-iso'
alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"

# Shorter commands
alias ..="cd .."
alias ...="cd ../.."
alias v="vim" # Typically use nvim, but also works if use normal vim
alias suvi="sudo vim"
alias md="mkdir -p"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Git
alias ga="git add"
alias gc="git commit"
alias gp="git pull"
alias gs="git status"
alias gch="git checkout"
alias gb="git branch"
alias gl="git log"
alias gr="git rebase"
alias gm="git merge"

# Distro-specific
. $XDG_CONFIG_HOME/bash/distro_aliases
